[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[project]
name = "requireris"
version = "2.0.0"

[project.urls]
homepage = "https://github.com/entwanne/requireris"

[project.scripts]
requireris = "requireris.__main__:main"
